#ESTE ARCHIVO SE VE SOBRE LA MANERA EN QUE PODEMOS HACER ALGUNA OPERACION
# EVITANDO EL PONER OTRA VARIABLE PARA PODER HACER UNA SUMA O ALGUNA OPERACION DE ASIGNACIÓN

miVarible = 10

print(miVarible)

#LO QUE QUIERE QUE ENTENDEMOS
miVarible = miVarible + 1

print(miVarible)

miVarible+=2

print(miVarible)