"""
    ESTE ARCHIVO SE VE SOBRE LA MANERA EN QUE PODEMOS HACER ALGUNA OPERACION.
    EVITANDO EL PONER OTRA VARIABLE PARA PODER HACER UNA SUMA O ALGUNA OPERACION DE ASIGNACIÓN

"""



miVarible = 10

print(miVarible)

#LO QUE QUIERE QUE ENTENDEMOS (MANERA 1)
miVarible = miVarible + 1

print(miVarible)

#MANERA 2
miVarible+=2

print(miVarible)